version: "3"

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  app:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    environment:
      GIN_MODE: "release"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "${API_PORT}:${DOCKER_API_PORT}"
    command: go run main.go
    links:
      - db
