version: "3"

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  couchbase:
    image: bentonam/couchbase-docker:latest
    environment:
      CLUSTER_USERNAME: ${COUCH_USER}
      CLUSTER_PASSWORD: ${COUCH_PASSWORD}
      COUCH_CLUSTER_NAME: ${POSTGRES_PORT}
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    volumes:
      - ./couchbase-data:/opt/couchbase/var

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: "${RABBIT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBIT_PASSWORD}"
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      NAME: rabbitmq

  app:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    environment:
      GIN_MODE: "release"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "${API_PORT}:${DOCKER_API_PORT}"
    command: go run main.go
    links:
      - db
      - couchbase
      - rabbit
